name: Release Stealth

on:
  push:
    branches:
      - plugin

permissions:
  contents: write  # Ensure write permissions for GITHUB_TOKEN

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: set env
      run: echo "NOW=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

    - name: Zip stealth folder
      run: zip -r stealth.zip ./ -x screenshots -x .git -x .github

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ env.NOW }}"
        release_name: "Release ${{ env.NOW }}"  # Release named with current date and time
        draft: false
        prerelease: false
        body: |
          This is an automated release for the Stealth WordPress hacking tools plugin created at ${{ env.NOW }}

    - name: Upload Zip to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./stealth.zip
        asset_name: stealth.zip
        asset_content_type: application/zip
