name: Release Stealth

on:
  push:
    paths:
      - 'stealth/**'  # Trigger only if changes are made in the stealth folder

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Zip stealth folder
      run: zip -r stealth.zip stealth

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "release-$(date +'%Y-%m-%d-%H%M%S')"  # Tag with current date and time (YYYY-MM-DD-HHMMSS)
        release_name: "Release $(date +'%Y-%m-%d %H:%M:%S')"  # Release named with current date and time
        draft: false
        prerelease: false

    - name: Upload Zip to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./stealth.zip
        asset_name: stealth.zip
        asset_content_type: application/zip
